apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nf-server
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nf-server
  template:
    metadata:
      labels:
        app: nf-server
    spec:
      containers:
      - name: nf-server
        image: gcr.io/google_containers/volume-nfs:0.8
        ports:
          - name: nfs
            containerPort: 2049
          - name: mountd
            containerPort: 20048
          - name: rpcbind
            containerPort: 111
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /exports
            name: nfs-disk
      volumes:
        - name: nfs-disk
          gcePersistentDisk:
            pdName: varnost-nfs-disk
            fsType: ext4