apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nfs-tester
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nfs-tester
  template:
    metadata:
      labels:
        app: nfs-tester
    spec:
      containers:
      - name: nfs-tester
        image: busybox
        command:
          - sh
          - -c
          - 'while true; do date > /mnt/index.html; hostname >> /mnt/index.html; sleep $(($RANDOM % 5 + 5)); done'
        imagePullPolicy: IfNotPresent
        name: busybox
        volumeMounts:
          - name: nfs
            mountPath: "/mnt"
      volumes:
      - name: nfs
        persistentVolumeClaim:
          claimName: nfs
