apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
     app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        resources:
          limits:
            cpu: 1000m
          requests:
            cpu: 100m
        ports:
        - containerPort: 5601
          name: kibana
        - containerPort: 8081
          name: flink
        - containerPort: 5044
          name: beats
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 60
          timeoutSeconds: 10
        volumeMounts:
          - name: config
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
            readOnly: true
          - name: nx-ssl
            mountPath: /etc/nginx-ssl
            readOnly: true
          - name: htpasswd
            mountPath: /etc/apache2/.htpasswd
            subPath: .htpasswd
            readOnly: true
      volumes:
        - name: config
          configMap:
            name: nginx-config
        - name: nx-ssl
          secret:
            secretName: nx-ssl
        - name: htpasswd
          secret:
            secretName: htpasswd