apiVersion: v1
kind: Service
metadata:
  name: nx-loadbalancer
spec:
  selector:
    app: nginx
  ports:
  - name: kibana
    port: 5601
  - name: flink
    port: 8081
  - name: beats
    port: 5044
  type: LoadBalancer
  # REPLACE WITH YOUR IP
  loadBalancerIP: "xxx.xxx.xxx.xxx"
