apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
data:
  tcp.conf: |
    input {
      tcp {
        port => 9999
      }
      beats {
        port => 5044
      }
    }
    output {
      elasticsearch {
        hosts => ["es-nodeport:9200"]
      }
      kafka {
        codec => json
        topic_id => "logs"
        bootstrap_servers => "kafka-0.kf-service.default.svc.cluster.local:9092,kafka-1.kf-service.default.svc.cluster.local:9092,kafka-2.kf-service.default.svc.cluster.local:9092"
      }
    }