apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: logstash
spec:
  serviceName: ls-service
  replicas: 2
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      terminationGracePeriodSeconds: 300
      initContainers:
      - name: fix-the-volume-permission
        image: busybox
        command:
        - sh
        - -c
        - chown -R 1000:1000 /usr/share/logstash/data
        securityContext:
          privileged: true
        volumeMounts:
        - name: data
          mountPath: /usr/share/logstash/data
      containers:
      - name: logstash
        image: varnost/logstash:6.5.4
        args: ["--config.reload.automatic"]
        ports:
        - containerPort: 9600
          name: http
        - containerPort: 5044
          name: beats
        - containerPort: 514
          name: syslog-udp
        - containerPort: 601
          name: syslog-conn
        - containerPort: 6514
          name: syslog-tls-tcp
        - containerPort: 9999
          name: raw-tcp
        resources:
          requests:
            memory: 500Mi
            cpu: 100m
          limits:
            memory: 1Gi
            cpu: 1000m
        env:
        - name: queue.type
          value: "persisted"
        - name: queue.max_bytes
          value: "4gb"
        - name: queue.drain
          value: "true"
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 60
          timeoutSeconds: 10
        volumeMounts:
        - name: pipeline
          mountPath: /usr/share/logstash/pipeline
          subPath: logstash
          readOnly: true
        - name: data
          mountPath: /usr/share/logstash/data
      volumes:
      - name: pipeline
        persistentVolumeClaim:
          claimName: nfs
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
        - ReadWriteOnce
      storageClassName: ssd
      resources:
        requests:
          storage: 5Gi