apiVersion: v1
kind: Service
metadata:
  name: ls-loadbalancer
spec:
  selector:
    app: logstash
  ports:
  - name: beats
    port: 5044
  type: LoadBalancer
                  # Replace this with your LB IP!
  loadBalancerIP: "xxx.xxx.xxx.xxx"
                  # Replace this with your LB IP!