apiVersion: v1
kind: Service
metadata:
  name: fl-service
spec:
  ports:
  - name: rpc
    port: 6123
  - name: blob
    port: 6124
  - name: query
    port: 6125
  - name: ui
    port: 8081
  - name: interprocess
    port: 50010
  selector:
    app: flink
    component: jobmanager
