apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-jobmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flink
      component: jobmanager
  template:
    metadata:
      labels:
        app: flink
        component: jobmanager
    spec:
      securityContext:
        fsGroup: 9999
      initContainers:
      - name: copy-configmap
        image: busybox
        command:
        - sh
        - -c
        - cp /configmap/flink-conf.yaml /mutableconfig/flink-conf.yaml
        volumeMounts:
        - name: config
          mountPath: /configmap/flink-conf.yaml
          subPath: flink-conf.yaml
        - name: instance-config
          mountPath: /mutableconfig
      containers:
      - name: flink-jobmanager
        image: varnost/flink:1.7.2-scala_2.12
        imagePullPolicy: Always
        args:
        - jobmanager
        ports:
        - containerPort: 6123
          name: rpc
        - containerPort: 6124
          name: blob
        - containerPort: 6125
          name: query
        - containerPort: 8081
          name: ui
        - containerPort: 50010
          name: interprocess
        volumeMounts:
        - name: instance-config
          mountPath: /opt/flink/conf/flink-conf.yaml
          subPath: flink-conf.yaml
        - name: config
          mountPath: /opt/flink/conf/masters
          subPath: masters
        - name: data
          mountPath: /opt/flink/checkpoints
          subPath: checkpoints
        - name: data
          mountPath: /opt/flink/savepoints
          subPath: savepoints
        - name: data
          mountPath: /opt/flink/ha-storage
          subPath: ha-storage
      volumes:
      - name: config
        configMap:
          name: flink-config
      - name: instance-config
        emptyDir: {}
      - name: data
        persistentVolumeClaim:
          claimName: data-flink-jobmanager