# TODO: Look into the following link for final deployments
# https://github.com/apache/flink/tree/release-1.7/flink-container/docker
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: flink-jobmanager
spec:
  selector:
    matchLabels:
      app: flink
      component: jobmanager
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: flink
        component: jobmanager
    spec:
      securityContext:
        fsGroup: 9999
      containers:
      - name: flink-jobmanager
        image: flink:1.7.1-scala_2.12
        args:
        - jobmanager
        ports:
        - containerPort: 6123
          name: rpc
        - containerPort: 6124
          name: blob
        - containerPort: 6125
          name: query
        - containerPort: 8081
          name: ui
        env:
        - name: JOB_MANAGER_RPC_ADDRESS
          value: fl-service
        volumeMounts:
          - name: config
            mountPath: /opt/flink/conf/flink-conf.yaml
            subPath: flink-conf.yaml
          - name: state
            mountPath: /opt/flink/checkpoints
            subPath: checkpoints
          - name: state
            mountPath: /opt/flink/savepoints
            subPath: savepoints
      volumes:
        - name: config
          configMap:
            name: flink-config
        - name: state
          persistentVolumeClaim:
            claimName: state-flink-jobmanager