apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: flink-taskmanager
spec:
  serviceName: fl-taskmanager-headless-service
  replicas: 3
  selector:
    matchLabels:
      app: flink
      component: taskmanager
  template:
    metadata:
      labels:
        app: flink
        component: taskmanager
    spec:
      securityContext:
        fsGroup: 9999
      initContainers:
      - name: copy-configmap
        image: busybox
        command:
        - sh
        - -c
        - cp /configmap/flink-conf.yaml /mutableconfig/flink-conf.yaml
        volumeMounts:
        - name: config
          mountPath: /configmap/flink-conf.yaml
          subPath: flink-conf.yaml
        - name: instance-config
          mountPath: /mutableconfig
      containers:
      - name: flink-taskmanager
        image: varnost/flink:1.7.2-scala_2.12
        imagePullPolicy: Always
        args:
        - taskmanager
        ports:
        - containerPort: 6121
          name: data
        - containerPort: 6122
          name: rpc
        - containerPort: 6125
          name: query
        - containerPort: 50011
          name: metrics
        volumeMounts:
        - name: instance-config
          mountPath: /opt/flink/conf/flink-conf.yaml
          subPath: flink-conf.yaml
        - name: data
          mountPath: /opt/flink/checkpoints
          subPath: checkpoints
        - name: data
          mountPath: /opt/flink/savepoints
          subPath: savepoints
      volumes:
        - name: config
          configMap:
            name: flink-config
        - name: instance-config
          emptyDir: {}
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
        - ReadWriteOnce
      storageClassName: ssd
      resources:
        requests:
          storage: 5Gi