apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: flink-taskmanager
spec:
  serviceName: fl-taskmanager-headless-service
  replicas: 3
  selector:
    matchLabels:
      app: flink
      component: taskmanager
  template:
    metadata:
      labels:
        app: flink
        component: taskmanager
    spec:
      securityContext:
        fsGroup: 9999
      containers:
      - name: flink-taskmanager
        image: flink:1.7.1-scala_2.12
        args:
        - taskmanager
        ports:
        - containerPort: 6121
          name: data
        - containerPort: 6122
          name: rpc
        - containerPort: 6125
          name: query
        volumeMounts:
          - name: config
            mountPath: /opt/flink/conf/flink-conf.yaml
            subPath: flink-conf.yaml
          - name: state
            mountPath: /opt/flink/checkpoints
            subPath: checkpoints
          - name: state
            mountPath: /opt/flink/savepoints
            subPath: savepoints
      volumes:
        - name: config
          configMap:
            name: flink-config
  volumeClaimTemplates:
  - metadata:
      name: state
    spec:
      accessModes:
        - ReadWriteOnce
      storageClassName: ssd
      resources:
        requests:
          storage: 5Gi