apiVersion: v1
kind: Service
metadata:
  name: fl-taskmanager-headless-service
spec:
  clusterIP: None
  ports:
  - name: rpc
    port: 6123
  - name: blob
    port: 6124
  - name: query
    port: 6125
  - name: ui
    port: 8081
  - name: metrics
    port: 50011
  selector:
    app: flink
    component: taskmanager